In [3]:
import numpy as np
#数组的索引和切片

In [4]:
a=np.array([9,8,7,6,5])
a[2]

7

In [5]:
#第一个表示开始的编号，即起始编号:终止编号(不含):步长
a[1:4:2]

array([8, 6])

In [6]:
#多维数组的索引和切片
a=np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [7]:
a[1,2,3]

23

In [8]:
a[0,1,2]

6

In [9]:
a[-1,-2,-3]

17

In [10]:
a[:1,-3]

array([[0, 1, 2, 3]])

In [11]:
a[:,1,-3]

array([ 5, 17])

In [12]:
a[:,1:3,:]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
#覆盖第一个维度所有范围，覆盖第二个维度所有范围，第三个维度，从头到尾不关心，要求以2位步长
a[:,:,::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])