In [ ]:
#数组与标量之间的运算
#数组与标量之间的运算作用于数组的每一个元素

In [4]:
#计算a与元素平均值的商
import numpy as np
a=np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
a.mean()

11.5

In [7]:
a=a/a.mean()
a

array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
        [0.34782609, 0.43478261, 0.52173913, 0.60869565],
        [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],

       [[1.04347826, 1.13043478, 1.2173913 , 1.30434783],
        [1.39130435, 1.47826087, 1.56521739, 1.65217391],
        [1.73913043, 1.82608696, 1.91304348, 2.        ]]])

In [8]:
a=np.arange(24).reshape((2,3,4))
#  np.square(a)  只是计算了值，没有生成数组
np.square(a)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]])

In [10]:
a=np.sqrt(a)
a

array([[[0.        , 1.        , 1.18920712, 1.31607401],
        [1.41421356, 1.49534878, 1.56508458, 1.62657656],
        [1.68179283, 1.73205081, 1.77827941, 1.82116029]],

       [[1.86120972, 1.89882892, 1.93433642, 1.96798967],
        [2.        , 2.03054318, 2.05976714, 2.08779763],
        [2.11474253, 2.14069514, 2.16573677, 2.1899387 ]]])

In [11]:
a=np.arange(24).reshape((2,3,4))
b=np.sqrt(a)
np.maximum(a,b)
#最后结果是浮点数（有整数和浮点数时，运算结果一般为浮点数）

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [12]:
a>b

array([[[False, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])