In [1]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
np.sum(a)

105

In [4]:
#axis代表轴，axis=1 将数组中第二维度的数据进行平均数运算
np.mean(a,axis=1)

array([ 2.,  7., 12.])

In [5]:
np.mean(a,axis=0)

array([5., 6., 7., 8., 9.])

In [7]:
np.average(a,axis=0,weights=[10,5,1])

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])