In [2]:
import numpy as np
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
a.ndim

1

In [4]:
a.shape

(20,)

In [5]:
a[3]

3

In [6]:
a[3]=100
print(a)

[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [7]:
np.empty((2,3))

array([[2.00000000e+000, 4.33995713e-311, 1.48219694e-323],
       [0.00000000e+000, 0.00000000e+000, 4.17201348e-309]])

In [8]:
np.full((2,2), 3)

array([[3, 3],
       [3, 3]])

In [9]:
#eye函数可以创建一个n * n矩阵，对角线为1s，其他为0,默认生成浮点数
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.zeros((3,6),dtype=np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [16]:
array = np.array([(1,2,3), (4,5,6)])
array.shape

(2, 3)

In [17]:
array.ndim

2

In [18]:
#创建一个填充0到1之间随机值的数组，请使用random函数
np.random.random((2,2))

array([[0.13728862, 0.43547662],
       [0.87520943, 0.40567805]])

In [25]:
a=np.linspace(1,10,4)
a

array([ 1.,  4.,  7., 10.])

In [27]:
#endpoint 表示新生成数组的最后一个元素是不是10
b=np.linspace(1,10,4,endpoint=False)
b

array([1.  , 3.25, 5.5 , 7.75])

In [28]:
#两个数组的合并
c=np.concatenate((a,b))
c

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

In [ ]:
#ndarray数组的维度变换
#.reshape(shape) 不改变数组元素，返回一个shape形状的数组，原数组不变
#.resize(shape)  与reshape()功能一致，但是修改原数组
#.swapaxes(ax1,ax2)  将数组n个维度中两个维度进行调换
#.flatten() 对数组进行降维，返回折叠后的一维数组，原数组不变

In [30]:
a=np.ones((2,3,4),dtype=np.int32)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [34]:
a=np.ones((2,3,4),dtype=np.int32)
a.reshape((3,8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [39]:
a=np.ones((2,3,4),dtype=np.int32)
a.resize((3,8))
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [38]:
a.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=int32)

In [45]:
#new_a=a.astype(new_type)
a=np.ones((2,3,4),dtype=np.int)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [47]:
#变为浮点数，astype一定是创建了新的数组
b=a.astype(np.float)
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [48]:
a=np.full((2,3,4),25,dtype=np.int)
a

array([[[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]],

       [[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]]])

In [49]:
#变为列表 
a.tolist()

[[[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]],
 [[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]]]