In [1]:
#最外层为三组，然后每组都是四行五列
#np.random.rand(3,4,5)  生成随机数，都是0-1之间的浮点数
import numpy as np
a=np.random.rand(3,4,5)
a

array([[[0.97638969, 0.93180189, 0.15061668, 0.92152622, 0.78076549],
        [0.55340213, 0.04261929, 0.88603516, 0.98013361, 0.76826973],
        [0.41431791, 0.00257023, 0.05665658, 0.01958953, 0.56259365],
        [0.07517183, 0.32009204, 0.66801589, 0.04441585, 0.98070846]],

       [[0.39609293, 0.6475492 , 0.50168738, 0.35648481, 0.5620597 ],
        [0.36045235, 0.92677461, 0.93472127, 0.39608829, 0.80341707],
        [0.79555518, 0.56714893, 0.25963613, 0.73798456, 0.45666743],
        [0.4672391 , 0.40239608, 0.80043136, 0.2301797 , 0.18227934]],

       [[0.43691601, 0.73086482, 0.71938101, 0.72750008, 0.49068845],
        [0.92029008, 0.69705485, 0.33694062, 0.83176258, 0.0602055 ],
        [0.32457186, 0.68214271, 0.80133525, 0.44033628, 0.43423765],
        [0.85390302, 0.05367023, 0.00182243, 0.3893366 , 0.75861339]]])

In [2]:
#np.random.randn(3,4,5)  生成随机数，都是0-1之间的浮点数，且呈现正态分布
sn=np.random.randn(3,4,5)
sn

array([[[-1.58561415,  0.75725851,  0.00401443,  0.26489104,
          0.82416639],
        [-0.29914593, -0.51775485, -0.56563285,  0.89969076,
          1.63234151],
        [ 1.49138626, -0.71494676, -0.58901107, -0.23769042,
         -0.40743102],
        [-0.37774271, -0.09803878, -0.25218822,  0.50212774,
          0.84886921]],

       [[ 1.39481209,  0.11115985,  0.01278647, -0.10435452,
          0.07682657],
        [-1.51660764,  0.5892783 ,  0.66075283, -0.24593205,
         -0.78198421],
        [ 0.03041266,  1.92253413,  1.4841899 ,  0.41133192,
          1.05179421],
        [-0.22048492,  0.51234905,  0.23617186,  0.46259872,
          0.09048126]],

       [[-0.88616753, -1.68069625, -1.15636443, -0.81513448,
          0.17551566],
        [ 1.12034083, -0.79093708,  1.24910051,  0.67051572,
         -0.01653401],
        [-0.99751611, -2.14735095, -1.32868751, -1.27215543,
         -1.89543277],
        [-0.30643437,  0.96981929,  0.15192823, -0.54755401,
         -0

In [3]:
#randint(100,200,(3,4))，取值在100-200之间，三行四列
b=np.random.randint(100,200,(3,4))
b

array([[171, 135, 178, 165],
       [161, 183, 165, 191],
       [139, 158, 179, 191]])

In [6]:
np.random.seed(10)
np.random.randint(100,200,(3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [ ]:
#shuffle(a),根据数组a的第1轴进行随排列，改变数组x
#permutation(a),根据数组a的第1轴产生一个新的乱序数组，不改变数组x
#choice(a[,size,replace,p]),从一维数组a中以概率p抽取元素，形成size形状新数组 replace表示是否可以重用元素，默认为False

In [7]:
import numpy as np
a=np.random.randint(100,200,(3,4))
a

array([[116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

In [8]:
np.random.shuffle(a)
a

array([[116, 111, 154, 188],
       [149, 151, 154, 177],
       [162, 133, 172, 178]])

In [9]:
import numpy as np
a=np.random.randint(100,200,(3,4))
a

array([[125, 113, 192, 186],
       [130, 130, 189, 112],
       [165, 131, 157, 136]])

In [11]:
b=np.random.permutation(a)
a

array([[125, 113, 192, 186],
       [130, 130, 189, 112],
       [165, 131, 157, 136]])

In [12]:
b

array([[165, 131, 157, 136],
       [125, 113, 192, 186],
       [130, 130, 189, 112]])

In [14]:
import numpy as np
b=np.random.randint(100,200,(8,))
b

array([123, 194, 111, 128, 174, 188, 109, 115])

In [15]:
np.random.choice(b,(3,2))

array([[111, 123],
       [109, 115],
       [123, 128]])

In [17]:
#replace=False  元素是否需要重复出现
np.random.choice(b,(3,2),replace=False)

array([[188, 111],
       [123, 115],
       [174, 128]])

In [18]:
#p=b/np.sum(b)为每个元素赋值抽取的概率
np.random.choice(b,(3,2),p=b/np.sum(b))

array([[194, 188],
       [109, 111],
       [174, 109]])

In [ ]:
#uniform(low,high,size)  产生具有均匀分布的数组,low起始值,high结束值,size形状
#normal(loc,scale,size)  产生具有正态分布的数组,loc均值,scale标准差,size形状
#poisson(lam,size)   产生具有泊松分布的数组,lam随机事件发生率,size形状